# Generated by Django 3.1.2 on 2020-10-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taiex",
            fields=[
                (
                    "trade_date",
                    models.DateField(
                        help_text="交易日期", primary_key=True, serialize=False
                    ),
                ),
                ("opening_price", models.FloatField(help_text="開盤價", null=True)),
                ("highest_price", models.FloatField(help_text="最高價", null=True)),
                ("lowest_price", models.FloatField(help_text="最低價", null=True)),
                ("closing_price", models.FloatField(help_text="收盤價", null=True)),
                ("trade_volume", models.BigIntegerField(help_text="成交股數", null=True)),
                ("trade_value", models.BigIntegerField(help_text="成交金額", null=True)),
                ("transaction", models.BigIntegerField(help_text="成交筆數", null=True)),
            ],
            options={
                "db_table": "taiex",
            },
        ),
    ]
