# Generated by Django 3.1.2 on 2020-10-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YearSeasonTableInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(help_text="年度", max_length=10)),
                ("season", models.CharField(help_text="季度", max_length=10)),
            ],
            options={
                "db_table": "year_season",
            },
        ),
        migrations.CreateModel(
            name="ComprehensiveIncome",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "net_income_loss_of_interest",
                    models.FloatField(help_text="利息淨收益", null=True),
                ),
                (
                    "net_non_interest_income_loss",
                    models.FloatField(help_text="利息以外淨損益", null=True),
                ),
                (
                    "total_bad_debts_expense_and_guarantee_liability_provision",
                    models.FloatField(help_text="呆帳費用及保證責任準備提存（各項提存）", null=True),
                ),
                (
                    "total_operating_expense",
                    models.FloatField(help_text="營業費用", null=True),
                ),
                (
                    "profit_loss_from_continuing_operations_before_tax",
                    models.FloatField(help_text="繼續營業單位稅前淨利（淨損）", null=True),
                ),
                (
                    "tax_income_expense",
                    models.FloatField(help_text="所得稅（費用）利益", null=True),
                ),
                (
                    "income_loss_from_continuing_operations_net_of_tax",
                    models.FloatField(help_text="繼續營業單位本期稅後淨利（淨損）", null=True),
                ),
                (
                    "total_income_loss_from_discontinued_operations",
                    models.FloatField(help_text="停業單位損益", null=True),
                ),
                (
                    "profit_loss_non_control_interest_before_combine_common_control",
                    models.FloatField(help_text="合併前非屬共同控制股權損益", null=True),
                ),
                ("profit_loss", models.FloatField(help_text="本期稅後淨利（淨損）", null=True)),
                (
                    "other_comprehensive_income_net_of_tax",
                    models.FloatField(help_text="其他綜合損益（稅後）", null=True),
                ),
                (
                    "total_comprehensive_income_net_of_tax",
                    models.FloatField(help_text="本期綜合損益總額（稅後）", null=True),
                ),
                (
                    "profit_loss_attributable_to_owners_of_parent",
                    models.FloatField(help_text="淨利（損）歸屬於母公司業主", null=True),
                ),
                (
                    "profit_loss_former_owner_business_combine_under_common_control",
                    models.FloatField(help_text="淨利（損）歸屬於共同控制下前手權益", null=True),
                ),
                (
                    "profit_loss_attributable_to_non_controlling_interests",
                    models.FloatField(help_text="淨利（損）歸屬於非控制權益", null=True),
                ),
                (
                    "comprehensive_income_attributable_to_owners_of_parent",
                    models.FloatField(help_text="綜合損益總額歸屬於母公司業主", null=True),
                ),
                (
                    "comprehensive_income_former_combine_under_common_control",
                    models.FloatField(help_text="綜合損益總額歸屬於共同控制下前手權益", null=True),
                ),
                (
                    "comprehensive_income_attributable_to_non_control_interests",
                    models.FloatField(help_text="綜合損益總額歸屬於非控制權益", null=True),
                ),
                (
                    "total_primary_earnings_per_share",
                    models.FloatField(help_text="基本每股盈餘（元）", null=True),
                ),
                ("total_revenue", models.FloatField(help_text="收益", null=True)),
                (
                    "total_expenditure_and_expense",
                    models.FloatField(help_text="支出及費用", null=True),
                ),
                (
                    "net_operating_income_loss",
                    models.FloatField(help_text="營業利益", null=True),
                ),
                (
                    "total_non_operating_income_and_expenses",
                    models.FloatField(help_text="營業外損益", null=True),
                ),
                (
                    "income_tax_benefit_expense",
                    models.FloatField(help_text="所得稅利益（費用）", null=True),
                ),
                (
                    "profit_loss_from_continuing_operations",
                    models.FloatField(help_text="繼續營業單位本期淨利（淨損）", null=True),
                ),
                (
                    "other_comprehensive_income",
                    models.FloatField(help_text="本期其他綜合損益（稅後淨額）", null=True),
                ),
                (
                    "comprehensive_income_non_interest_before_combine_commoncontrol",
                    models.FloatField(help_text="合併前非屬共同控制股權綜合損益淨額", null=True),
                ),
                (
                    "total_comprehensive_income",
                    models.FloatField(help_text="本期綜合損益總額", null=True),
                ),
                (
                    "total_operating_revenue",
                    models.FloatField(help_text="營業收入", null=True),
                ),
                (
                    "total_operating_costs",
                    models.FloatField(help_text="營業成本", null=True),
                ),
                (
                    "gross_profit_loss_from_operations",
                    models.FloatField(help_text="營業毛利（毛損）", null=True),
                ),
                (
                    "unrealized_profit_loss_from_sales",
                    models.FloatField(help_text="未實現銷貨（損）益", null=True),
                ),
                (
                    "realized_profit_loss_on_from_sales",
                    models.FloatField(help_text="已實現銷貨（損）益", null=True),
                ),
                (
                    "gross_profit_loss_from_operations_net",
                    models.FloatField(help_text="營業毛利（毛損）淨額", null=True),
                ),
                (
                    "net_other_income_expenses",
                    models.FloatField(help_text="其他收益及費損淨額", null=True),
                ),
                (
                    "total_tax_expense_income",
                    models.FloatField(help_text="所得稅費用（利益）", null=True),
                ),
                (
                    "other_comprehensive_income_net",
                    models.FloatField(help_text="其他綜合損益（淨額）", null=True),
                ),
                (
                    "net_income_loss_except_interest",
                    models.FloatField(help_text="利息以外淨收益", null=True),
                ),
                ("net_income_loss", models.FloatField(help_text="淨收益", null=True)),
                (
                    "total_bad_debt_expenses_and_guarantee_liability_provisions",
                    models.FloatField(help_text="呆帳費用及保證責任準備提存", null=True),
                ),
                (
                    "total_net_change_in_provisions_for_insurance_liabilities",
                    models.FloatField(help_text="保險負債準備淨變動", null=True),
                ),
                (
                    "income_loss_from_continuing_operations",
                    models.FloatField(help_text="繼續營業單位稅前損益", null=True),
                ),
                (
                    "profit_loss_from_continuing_operations_before_income_tax",
                    models.FloatField(help_text="繼續營業單位稅前純益（純損）", null=True),
                ),
                (
                    "total_other_comprehensive_income",
                    models.FloatField(help_text="其他綜合損益（稅後淨額）", null=True),
                ),
                ("total_expenses", models.FloatField(help_text="支出", null=True)),
                (
                    "gains_loss_recognition_of_biological_asset_agriculture_produce",
                    models.FloatField(help_text="原始認列生物資產及農產品之利益（損失）", null=True),
                ),
                (
                    "gain_loss_arise_change_fair_value_costs_biological_asset",
                    models.FloatField(help_text="生物資產當期公允價值減出售成本之變動利益（損失）", null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="公司表代號",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "year_season",
                    models.ForeignKey(
                        help_text="年及季節代號",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundamentals.yearseasontableinfo",
                    ),
                ),
            ],
            options={
                "db_table": "comprehensive_income",
            },
        ),
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cash_and_cash_equivalent",
                    models.FloatField(help_text="現金及約當現金", null=True),
                ),
                (
                    "total_due_from_central_bank_and_call_loan_to_bank",
                    models.FloatField(help_text="存放央行及拆借銀行同業", null=True),
                ),
                (
                    "total_financial_assets_at_fair_value_through_profit_or_loss",
                    models.FloatField(help_text="透過損益按公允價值衡量之金融資產", null=True),
                ),
                (
                    "derivative_financial_asset_for_hedging_net",
                    models.FloatField(help_text="避險之衍生金融資產淨額", null=True),
                ),
                (
                    "securitie_purchased_under_resell_agreement_net",
                    models.FloatField(help_text="附賣回票券及債券投資淨額", null=True),
                ),
                (
                    "total_current_tax_asset",
                    models.FloatField(help_text="當期所得稅資產", null=True),
                ),
                (
                    "discounts_and_loans_net",
                    models.FloatField(help_text="貼現及放款－淨額", null=True),
                ),
                (
                    "available_for_sale_financial_assets_net",
                    models.FloatField(help_text="備供出售金融資產－淨額", null=True),
                ),
                (
                    "held_to_maturity_financial_assets_net",
                    models.FloatField(help_text="持有至到期日金融資產－淨額", null=True),
                ),
                (
                    "investments_measured_by_equity_method_net",
                    models.FloatField(help_text="採用權益法之投資－淨額", null=True),
                ),
                (
                    "restricted_assets_net",
                    models.FloatField(help_text="受限制資產－淨額", null=True),
                ),
                (
                    "other_financial_assets_net",
                    models.FloatField(help_text="其他金融資產－淨額", null=True),
                ),
                (
                    "property_and_equipment_net",
                    models.FloatField(help_text="不動產及設備－淨額", null=True),
                ),
                (
                    "investment_property_invest_net",
                    models.FloatField(help_text="投資性不動產投資－淨額", null=True),
                ),
                (
                    "intangible_assets_net",
                    models.FloatField(help_text="無形資產－淨額", null=True),
                ),
                (
                    "total_deferred_tax_assets",
                    models.FloatField(help_text="遞延所得稅資產", null=True),
                ),
                ("other_assets_net", models.FloatField(help_text="其他資產－淨額", null=True)),
                ("total_assets", models.FloatField(help_text="資產總額", null=True)),
                (
                    "total_deposits_from_the_central_bank_and_banks",
                    models.FloatField(help_text="央行及銀行同業存款", null=True),
                ),
                (
                    "total_due_to_the_central_bank_and_banks",
                    models.FloatField(help_text="央行及同業融資", null=True),
                ),
                (
                    "total_financial_liabilities_at_fair_value_profit_or_loss",
                    models.FloatField(help_text="透過損益按公允價值衡量之金融負債", null=True),
                ),
                (
                    "hedge_derivative_financial_liability_net",
                    models.FloatField(help_text="避險之衍生金融負債－淨額", null=True),
                ),
                (
                    "total_notes_and_bonds_issued_under_repurchase_agreement",
                    models.FloatField(help_text="附買回票券及債券負債", null=True),
                ),
                ("total_payables", models.FloatField(help_text="應付款項", null=True)),
                (
                    "total_current_tax_liabilities",
                    models.FloatField(help_text="當期所得稅負債", null=True),
                ),
                (
                    "total_liabilities_related_assets_classified_held_for_sale",
                    models.FloatField(help_text="與待出售資產直接相關之負債", null=True),
                ),
                (
                    "total_deposits_and_remittances",
                    models.FloatField(help_text="存款及匯款", null=True),
                ),
                (
                    "total_bank_notes_payable",
                    models.FloatField(help_text="應付金融債券", null=True),
                ),
                (
                    "total_bonds_payable",
                    models.FloatField(help_text="應付公司債", null=True),
                ),
                (
                    "total_preferred_stock_liabilities",
                    models.FloatField(help_text="特別股負債", null=True),
                ),
                (
                    "total_other_financial_liabilities",
                    models.FloatField(help_text="其他金融負債", null=True),
                ),
                ("total_provisions", models.FloatField(help_text="負債準備", null=True)),
                (
                    "total_deferred_income_tax_liabilities",
                    models.FloatField(help_text="遞延所得稅負債", null=True),
                ),
                (
                    "total_other_liabilities",
                    models.FloatField(help_text="其他負債", null=True),
                ),
                ("total_liabilities", models.FloatField(help_text="負債總額", null=True)),
                ("total_capital", models.FloatField(help_text="股本", null=True)),
                (
                    "total_capital_surplus",
                    models.FloatField(help_text="資本公積", null=True),
                ),
                (
                    "total_retained_earnings",
                    models.FloatField(help_text="保留盈餘", null=True),
                ),
                (
                    "total_other_equity_interest",
                    models.FloatField(help_text="其他權益", null=True),
                ),
                (
                    "total_treasury_shares",
                    models.FloatField(help_text="庫藏股票", null=True),
                ),
                (
                    "total_equity_attributable_to_owners_of_parent",
                    models.FloatField(help_text="歸屬於母公司業主之權益合計", null=True),
                ),
                (
                    "equity_to_former_owner_business_combination_common_control",
                    models.FloatField(help_text="共同控制下前手權益", null=True),
                ),
                (
                    "equity_non_control_interest_business_combine_common_control",
                    models.FloatField(help_text="合併前非屬共同控制股權", null=True),
                ),
                (
                    "total_non_controlling_interests",
                    models.FloatField(help_text="非控制權益", null=True),
                ),
                ("total_equity", models.FloatField(help_text="權益總額", null=True)),
                (
                    "number_of_share_capital_awaiting_retirement",
                    models.FloatField(help_text="待註銷股本股數（單位：股）", null=True),
                ),
                (
                    "number_treasury_share_acquired_by_company_and_subsidiaries",
                    models.FloatField(help_text="母公司暨子公司所持有之母公司庫藏股股數（單位：股）", null=True),
                ),
                (
                    "equivalent_issued_shares_of_advance_receipts_for_common_stock",
                    models.FloatField(help_text="預收股款（權益項下）之約當發行股數（單位：股）", null=True),
                ),
                (
                    "book_value_per_share",
                    models.FloatField(help_text="每股參考淨值", null=True),
                ),
                (
                    "total_current_assets",
                    models.FloatField(help_text="流動資產", null=True),
                ),
                (
                    "non_current_assets_net",
                    models.FloatField(help_text="非流動資產", null=True),
                ),
                (
                    "total_current_liabilities",
                    models.FloatField(help_text="流動負債", null=True),
                ),
                (
                    "total_non_current_liabilities",
                    models.FloatField(help_text="非流動負債", null=True),
                ),
                ("equity", models.FloatField(help_text="權益合計", null=True)),
                (
                    "number_of_shares_entity_held_entity_and_its_subsidiaries",
                    models.FloatField(help_text="母公司暨子公司持有之母公司庫藏股股數（單位：股）", null=True),
                ),
                (
                    "due_from_the_central_bank_and_call_loans_to_banks",
                    models.FloatField(help_text="存放央行及拆借金融同業", null=True),
                ),
                (
                    "derivative_financial_assets_for_hedging",
                    models.FloatField(help_text="避險之衍生金融資產", null=True),
                ),
                (
                    "securities_purchased_under_resell_agreements",
                    models.FloatField(help_text="附賣回票券及債券投資", null=True),
                ),
                (
                    "reinsurance_contract_assets_net",
                    models.FloatField(help_text="再保險合約資產－淨額", null=True),
                ),
                (
                    "investment_property_net",
                    models.FloatField(help_text="投資性不動產－淨額", null=True),
                ),
                (
                    "deposits_from_the_central_bank_and_banks",
                    models.FloatField(help_text="央行及金融同業存款", null=True),
                ),
                (
                    "derivative_financial_liabilities_for_hedging",
                    models.FloatField(help_text="避險之衍生金融負債", null=True),
                ),
                (
                    "commercial_papers_issued_net",
                    models.FloatField(help_text="應付商業本票－淨額", null=True),
                ),
                ("bonds_payable", models.FloatField(help_text="應付債券", null=True)),
                (
                    "total_other_borrowings",
                    models.FloatField(help_text="其他借款", null=True),
                ),
                ("receivables_net", models.FloatField(help_text="應收款項", null=True)),
                (
                    "assets_classified_as_held_for_sale_net",
                    models.FloatField(help_text="待出售資產", null=True),
                ),
                (
                    "non_current_asset_disposal_group_held_distribution_owners",
                    models.FloatField(help_text="待分配予業主之資產（或處分群組）", null=True),
                ),
                ("total_investments", models.FloatField(help_text="投資", null=True)),
                (
                    "total_reinsurance_assets",
                    models.FloatField(help_text="再保險合約資產", null=True),
                ),
                (
                    "total_property_and_equipment",
                    models.FloatField(help_text="不動產及設備", null=True),
                ),
                (
                    "total_intangible_assets",
                    models.FloatField(help_text="無形資產", null=True),
                ),
                ("total_other_assets", models.FloatField(help_text="其他資產", null=True)),
                (
                    "assets_on_insurance_product_separated_account",
                    models.FloatField(help_text="分離帳戶保險商品資產", null=True),
                ),
                (
                    "short_term_liabilities_net",
                    models.FloatField(help_text="短期債務", null=True),
                ),
                (
                    "financial_liabilities_at_cost",
                    models.FloatField(help_text="以成本衡量之金融負債", null=True),
                ),
                (
                    "total_insurance_liabilities",
                    models.FloatField(help_text="保險負債", null=True),
                ),
                (
                    "reserve_for_insurance_with_nature_of_financial_instrument",
                    models.FloatField(help_text="具金融商品性質之保險契約準備", null=True),
                ),
                (
                    "reserve_for_foreign_exchange_valuation",
                    models.FloatField(help_text="外匯價格變動準備", null=True),
                ),
                (
                    "liabilities_on_insurance_product_separated_account",
                    models.FloatField(help_text="分離帳戶保險商品負債", null=True),
                ),
                ("treasury_shares", models.FloatField(help_text="庫藏股", null=True)),
                (
                    "assets_classified_as_held_for_distribution_to_owners_net",
                    models.FloatField(help_text="待分配予業主之資產－淨額", null=True),
                ),
                (
                    "financial_assets_fair_value_other_comprehensive_income",
                    models.FloatField(help_text="透過其他綜合損益按公允價值衡量之金融資產", null=True),
                ),
                (
                    "investments_in_debt_instruments_at_amortised_cost",
                    models.FloatField(help_text="按攤銷後成本衡量之債務工具投資", null=True),
                ),
                (
                    "current_tax_assets",
                    models.FloatField(help_text="本期所得稅資產", null=True),
                ),
                (
                    "right_of_use_assets_net",
                    models.FloatField(help_text="使用權資產－淨額", null=True),
                ),
                ("lease_liabilities", models.FloatField(help_text="租賃負債", null=True)),
                (
                    "right_of_use_assets",
                    models.FloatField(help_text="使用權資產", null=True),
                ),
                (
                    "total_equity_security_token_Offer",
                    models.FloatField(help_text="權益─具證券性質之虛擬通貨", null=True),
                ),
                (
                    "equity_security_token_Offer",
                    models.FloatField(help_text="權益－具證券性質之虛擬通貨", null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="公司表代號",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "year_season",
                    models.ForeignKey(
                        help_text="年及季節代號",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fundamentals.yearseasontableinfo",
                    ),
                ),
            ],
            options={
                "db_table": "balance_sheet",
            },
        ),
    ]
