apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.database.name }}
  labels:
    app: {{ .Values.application.database.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.application.database.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.application.database.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "finance.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.database.repository }}:{{ .Values.image.database.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.database.pullPolicy }}
          ports:
            - name: {{ .Values.service.database.targetPort }}
              containerPort: {{ .Values.service.database.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.database.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.database.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.application.database.name }}
          volumeMounts:
            - name: database
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: local-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
