apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.database.name }}
  annotations:
    {{- toYaml .Values.secret | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 
  POSTGRES_DB: 
