apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.broker.name }}
  annotations:
    {{- toYaml .Values.secret | nindent 4 }}
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: 
  RABBITMQ_DEFAULT_PASS: 
  RABBITMQ_DEFAULT_VHOST:
