# Generated by Django 3.1.2 on 2020-10-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_type", models.CharField(help_text="產業類別", max_length=50)),
            ],
            options={
                "db_table": "company_type",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_code", models.CharField(help_text="公司代號", max_length=50)),
                ("company_name", models.CharField(help_text="公司名稱", max_length=50)),
                (
                    "company_abbreviation",
                    models.CharField(help_text="公司簡稱", max_length=50),
                ),
                (
                    "company_type",
                    models.ForeignKey(
                        help_text="公司種類ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companytype",
                    ),
                ),
            ],
            options={
                "db_table": "company",
            },
        ),
    ]
