# Generated by Django 3.2 on 2021-04-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.ForeignKey(
                help_text="公司種類ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="company.companytype",
            ),
        ),
    ]
