apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.backend.name }}
  annotations:
    {{- toYaml .Values.secret | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: 
  REDIS_URL: 
  DATABASE_URL: 
  BROKER_URL: 
  POSTGRESQL_HOST: 
  POSTGRESQL_PORT: 

