# Generated by Django 3.1.2 on 2020-10-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(help_text="交易日期", null=True)),
                ("opening_price", models.FloatField(help_text="開盤價", null=True)),
                ("highest_price", models.FloatField(help_text="最高價", null=True)),
                ("lowest_price", models.FloatField(help_text="最低價", null=True)),
                ("closing_price", models.FloatField(help_text="收盤價", null=True)),
                ("trade_volume", models.BigIntegerField(help_text="成交股數", null=True)),
                ("trade_value", models.BigIntegerField(help_text="成交金額", null=True)),
                ("transaction", models.BigIntegerField(help_text="成交筆數", null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="公司表ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
            },
        ),
    ]
