# Default values for finance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  backend:
    repository: localhost:5000/stock-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.0.1"
  database:
    repository: localhost:5000/postgres
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "12"
  cache:
    repository: localhost:5000/redis
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "6.2.1-alpine"
  broker:
    repository: rabbitmq
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "3.8.17-management"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

application:
  backend:
    name: backend
  database:
    name: database
  cache:
    name: cache
  broker:
    name: broker

service:
  backend:
    targetPort: backend-port
    type: ClusterIP
    port: 8000
  database:
    targetPort: database-port
    type: NodePort
    port: 5432
    nodePort: 31936
  cache:
    targetPort: cache-port
    type: ClusterIP
    port: 6379
  broker:
    queue:
      name: queue
      targetPort: queue-port
      type: ClusterIP
      port: 5672
    interface:
      name: interface
      targetPort: broker-port
      type: ClusterIP
      port: 15672

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: localhost
      paths:
      - path: /api
        backend:
          serviceName: backend
          servicePort: 8000
      - path: /static
        backend:
          serviceName: backend
          servicePort: 8000
      - path: /broker
        backend:
          serviceName: broker
          servicePort: 15672

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

secret: {}
